// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUh1Sh-TNtNyI-d2XtVUWzR1nXHK5bnic',
    appId: '1:1020768668022:web:dc932827ded064d8eb9257',
    messagingSenderId: '1020768668022',
    projectId: 'gauge-31025',
    authDomain: 'gauge-31025.firebaseapp.com',
    storageBucket: 'gauge-31025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9grkCi6Nn8tzKWTesAMIx4iX5lnd0HI',
    appId: '1:1020768668022:android:c8008a8281fd0d89eb9257',
    messagingSenderId: '1020768668022',
    projectId: 'gauge-31025',
    storageBucket: 'gauge-31025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1F7B62pq1pyv0habJqzHedUu8ViI1IJw',
    appId: '1:1020768668022:ios:c61866e89a1ec39beb9257',
    messagingSenderId: '1020768668022',
    projectId: 'gauge-31025',
    storageBucket: 'gauge-31025.firebasestorage.app',
    iosBundleId: 'com.gauge.gauge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1F7B62pq1pyv0habJqzHedUu8ViI1IJw',
    appId: '1:1020768668022:ios:c61866e89a1ec39beb9257',
    messagingSenderId: '1020768668022',
    projectId: 'gauge-31025',
    storageBucket: 'gauge-31025.firebasestorage.app',
    iosBundleId: 'com.gauge.gauge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUh1Sh-TNtNyI-d2XtVUWzR1nXHK5bnic',
    appId: '1:1020768668022:web:56899d68d7286a21eb9257',
    messagingSenderId: '1020768668022',
    projectId: 'gauge-31025',
    authDomain: 'gauge-31025.firebaseapp.com',
    storageBucket: 'gauge-31025.firebasestorage.app',
  );
}
