// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNAJZweTNk2L81w48sGrx62gNOgdPO3w',
    appId: '1:545817570266:web:35c8d10d57c5b746ac2ee3',
    messagingSenderId: '545817570266',
    projectId: 'eegcellent',
    authDomain: 'eegcellent.firebaseapp.com',
    storageBucket: 'eegcellent.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQtqqhD-Ia4JoLBja6JLP-vsLw-eYpzU',
    appId: '1:545817570266:android:bd4a0a3ac194c3aeac2ee3',
    messagingSenderId: '545817570266',
    projectId: 'eegcellent',
    storageBucket: 'eegcellent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RaLTFWaQWbSlcvcnAGgDMnpghSM5mJo',
    appId: '1:545817570266:ios:f54e98bab2a95f13ac2ee3',
    messagingSenderId: '545817570266',
    projectId: 'eegcellent',
    storageBucket: 'eegcellent.firebasestorage.app',
    iosBundleId: 'com.example.eegcellent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5RaLTFWaQWbSlcvcnAGgDMnpghSM5mJo',
    appId: '1:545817570266:ios:f54e98bab2a95f13ac2ee3',
    messagingSenderId: '545817570266',
    projectId: 'eegcellent',
    storageBucket: 'eegcellent.firebasestorage.app',
    iosBundleId: 'com.example.eegcellent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNAJZweTNk2L81w48sGrx62gNOgdPO3w',
    appId: '1:545817570266:web:9137d212f0e39450ac2ee3',
    messagingSenderId: '545817570266',
    projectId: 'eegcellent',
    authDomain: 'eegcellent.firebaseapp.com',
    storageBucket: 'eegcellent.firebasestorage.app',
  );

}